import * as XLSX from "xlsx";
import moment from "moment";
import { addThounsandSeparators } from "./helper";

/**
 * Generate Excel report for expenses with enhanced styling and formatting
 * @param {Array} expenseData - Array of expense objects
 * @param {string} fileName - Name of the file to download
 */
export const generateExpenseExcelReport = (expenseData, fileName = "Expense_Report") => {
  // Prepare data for Excel
  const worksheetData = [];

  // Add title row
  worksheetData.push(["EXPENSE REPORT"]);
  worksheetData.push([`Generated on: ${moment().format("DD MMMM YYYY, HH:mm")}`]);
  worksheetData.push([]); // Empty row for spacing

  // Calculate summary statistics
  const totalExpense = expenseData.reduce((sum, item) => sum + Number(item.amount), 0);
  const averageExpense = expenseData.length > 0 ? totalExpense / expenseData.length : 0;
  const maxExpense = expenseData.length > 0 ? Math.max(...expenseData.map(item => Number(item.amount))) : 0;
  const minExpense = expenseData.length > 0 ? Math.min(...expenseData.map(item => Number(item.amount))) : 0;

  // Add summary section
  worksheetData.push(["SUMMARY"]);
  worksheetData.push(["Total Expenses:", `Rp ${addThounsandSeparators(totalExpense)}`]);
  worksheetData.push(["Average Expense:", `Rp ${addThounsandSeparators(averageExpense.toFixed(2))}`]);
  worksheetData.push(["Highest Expense:", `Rp ${addThounsandSeparators(maxExpense)}`]);
  worksheetData.push(["Lowest Expense:", `Rp ${addThounsandSeparators(minExpense)}`]);
  worksheetData.push(["Total Transactions:", expenseData.length]);
  worksheetData.push([]); // Empty row for spacing

  // Add table headers
  worksheetData.push(["No.", "Source", "Amount (Rp)", "Date", "Month", "Year"]);

  // Add expense data
  expenseData.forEach((expense, index) => {
    worksheetData.push([
      index + 1,
      expense.source,
      addThounsandSeparators(expense.amount),
      moment(expense.date).format("DD/MM/YYYY"),
      moment(expense.date).format("MMMM"),
      moment(expense.date).format("YYYY"),
    ]);
  });

  // Add footer
  worksheetData.push([]);
  worksheetData.push(["Report generated by Finance App"]);
  worksheetData.push([`© ${moment().format("YYYY")} - All Rights Reserved`]);

  // Create workbook and worksheet
  const workbook = XLSX.utils.book_new();
  const worksheet = XLSX.utils.aoa_to_sheet(worksheetData);

  // Set column widths
  worksheet["!cols"] = [
    { wch: 6 },  // No.
    { wch: 25 }, // Source
    { wch: 18 }, // Amount
    { wch: 15 }, // Date
    { wch: 12 }, // Month
    { wch: 8 },  // Year
  ];

  // Merge cells for title
  worksheet["!merges"] = [
    { s: { r: 0, c: 0 }, e: { r: 0, c: 5 } }, // Title row
    { s: { r: 1, c: 0 }, e: { r: 1, c: 5 } }, // Date row
    { s: { r: 3, c: 0 }, e: { r: 3, c: 5 } }, // SUMMARY title
  ];

  // Add worksheet to workbook
  XLSX.utils.book_append_sheet(workbook, worksheet, "Expense Report");

  // Generate file name with timestamp
  const timestamp = moment().format("YYYYMMDD_HHmmss");
  const fullFileName = `${fileName}_${timestamp}.xlsx`;

  // Write and download file
  XLSX.writeFile(workbook, fullFileName);

  return fullFileName;
};

/**
 * Generate Excel report for income with enhanced styling and formatting
 * @param {Array} incomeData - Array of income objects
 * @param {string} fileName - Name of the file to download
 */
export const generateIncomeExcelReport = (incomeData, fileName = "Income_Report") => {
  // Prepare data for Excel
  const worksheetData = [];

  // Add title row
  worksheetData.push(["INCOME REPORT"]);
  worksheetData.push([`Generated on: ${moment().format("DD MMMM YYYY, HH:mm")}`]);
  worksheetData.push([]); // Empty row for spacing

  // Calculate summary statistics
  const totalIncome = incomeData.reduce((sum, item) => sum + Number(item.amount), 0);
  const averageIncome = incomeData.length > 0 ? totalIncome / incomeData.length : 0;
  const maxIncome = incomeData.length > 0 ? Math.max(...incomeData.map(item => Number(item.amount))) : 0;
  const minIncome = incomeData.length > 0 ? Math.min(...incomeData.map(item => Number(item.amount))) : 0;

  // Add summary section
  worksheetData.push(["SUMMARY"]);
  worksheetData.push(["Total Income:", `Rp ${addThounsandSeparators(totalIncome)}`]);
  worksheetData.push(["Average Income:", `Rp ${addThounsandSeparators(averageIncome.toFixed(2))}`]);
  worksheetData.push(["Highest Income:", `Rp ${addThounsandSeparators(maxIncome)}`]);
  worksheetData.push(["Lowest Income:", `Rp ${addThounsandSeparators(minIncome)}`]);
  worksheetData.push(["Total Transactions:", incomeData.length]);
  worksheetData.push([]); // Empty row for spacing

  // Add table headers
  worksheetData.push(["No.", "Source", "Amount (Rp)", "Date", "Month", "Year"]);

  // Add income data
  incomeData.forEach((income, index) => {
    worksheetData.push([
      index + 1,
      income.source,
      addThounsandSeparators(income.amount),
      moment(income.date).format("DD/MM/YYYY"),
      moment(income.date).format("MMMM"),
      moment(income.date).format("YYYY"),
    ]);
  });

  // Add footer
  worksheetData.push([]);
  worksheetData.push(["Report generated by Finance App"]);
  worksheetData.push([`© ${moment().format("YYYY")} - All Rights Reserved`]);

  // Create workbook and worksheet
  const workbook = XLSX.utils.book_new();
  const worksheet = XLSX.utils.aoa_to_sheet(worksheetData);

  // Set column widths
  worksheet["!cols"] = [
    { wch: 6 },  // No.
    { wch: 25 }, // Source
    { wch: 18 }, // Amount
    { wch: 15 }, // Date
    { wch: 12 }, // Month
    { wch: 8 },  // Year
  ];

  // Merge cells for title
  worksheet["!merges"] = [
    { s: { r: 0, c: 0 }, e: { r: 0, c: 5 } }, // Title row
    { s: { r: 1, c: 0 }, e: { r: 1, c: 5 } }, // Date row
    { s: { r: 3, c: 0 }, e: { r: 3, c: 5 } }, // SUMMARY title
  ];

  // Add worksheet to workbook
  XLSX.utils.book_append_sheet(workbook, worksheet, "Income Report");

  // Generate file name with timestamp
  const timestamp = moment().format("YYYYMMDD_HHmmss");
  const fullFileName = `${fileName}_${timestamp}.xlsx`;

  // Write and download file
  XLSX.writeFile(workbook, fullFileName);

  return fullFileName;
};
