import * as XLSX from "xlsx-js-style";
import moment from "moment";
import { addThounsandSeparators } from "./helper";

/**
 * Generate Excel report for expenses with enhanced styling and formatting
 * @param {Array} expenseData - Array of expense objects
 * @param {string} fileName - Name of the file to download
 */
export const generateExpenseExcelReport = (
  expenseData,
  fileName = "Expense_Report"
) => {
  // Prepare data for Excel
  const worksheetData = [];

  // Add title row
  worksheetData.push(["EXPENSE REPORT"]);
  worksheetData.push([
    `Generated on: ${moment().format("DD MMMM YYYY, HH:mm")}`,
  ]);
  worksheetData.push([]); // Empty row for spacing

  // Calculate summary statistics
  const totalExpense = expenseData.reduce(
    (sum, item) => sum + Number(item.amount),
    0
  );
  const averageExpense =
    expenseData.length > 0 ? totalExpense / expenseData.length : 0;
  const maxExpense =
    expenseData.length > 0
      ? Math.max(...expenseData.map((item) => Number(item.amount)))
      : 0;
  const minExpense =
    expenseData.length > 0
      ? Math.min(...expenseData.map((item) => Number(item.amount)))
      : 0;

  // Add summary section
  worksheetData.push(["SUMMARY"]);
  worksheetData.push([
    "Total Expenses:",
    `Rp ${addThounsandSeparators(totalExpense)}`,
  ]);
  worksheetData.push([
    "Average Expense:",
    `Rp ${addThounsandSeparators(averageExpense.toFixed(2))}`,
  ]);
  worksheetData.push([
    "Highest Expense:",
    `Rp ${addThounsandSeparators(maxExpense)}`,
  ]);
  worksheetData.push([
    "Lowest Expense:",
    `Rp ${addThounsandSeparators(minExpense)}`,
  ]);
  worksheetData.push(["Total Transactions:", expenseData.length]);
  worksheetData.push([]); // Empty row for spacing

  // Add table headers
  worksheetData.push(["No.", "Source", "Amount (Rp)", "Date", "Month", "Year"]);

  // Add expense data
  expenseData.forEach((expense, index) => {
    worksheetData.push([
      index + 1,
      expense.source,
      addThounsandSeparators(expense.amount),
      moment(expense.date).format("DD/MM/YYYY"),
      moment(expense.date).format("MMMM"),
      moment(expense.date).format("YYYY"),
    ]);
  });

  // Add footer
  worksheetData.push([]);
  worksheetData.push(["Report generated by Finance App"]);
  worksheetData.push([`© ${moment().format("YYYY")} - All Rights Reserved`]);

  // Create workbook and worksheet
  const workbook = XLSX.utils.book_new();
  const worksheet = XLSX.utils.aoa_to_sheet(worksheetData);

  // Set column widths - increased for better visibility
  worksheet["!cols"] = [
    { wch: 22 }, // No. / Summary Labels (expanded for "Total Transactions:")
    { wch: 30 }, // Source
    { wch: 20 }, // Amount
    { wch: 15 }, // Date
    { wch: 15 }, // Month
    { wch: 10 }, // Year
  ];

  // Merge cells for title
  worksheet["!merges"] = [
    { s: { r: 0, c: 0 }, e: { r: 0, c: 5 } }, // Title row
    { s: { r: 1, c: 0 }, e: { r: 1, c: 5 } }, // Date row
    { s: { r: 3, c: 0 }, e: { r: 3, c: 5 } }, // SUMMARY title
  ];

  // Apply styles to cells
  const range = XLSX.utils.decode_range(worksheet["!ref"]);

  // Style for title (row 0)
  for (let C = range.s.c; C <= range.e.c; ++C) {
    const address = XLSX.utils.encode_cell({ r: 0, c: C });
    if (!worksheet[address]) continue;
    worksheet[address].s = {
      font: { bold: true, sz: 16, color: { rgb: "FFFFFF" } },
      fill: { fgColor: { rgb: "1E3A8A" } }, // Dark blue
      alignment: { horizontal: "center", vertical: "center" },
    };
  }

  // Style for generated date (row 1)
  for (let C = range.s.c; C <= range.e.c; ++C) {
    const address = XLSX.utils.encode_cell({ r: 1, c: C });
    if (!worksheet[address]) continue;
    worksheet[address].s = {
      font: { italic: true, sz: 10 },
      alignment: { horizontal: "center", vertical: "center" },
      fill: { fgColor: { rgb: "E0E7FF" } }, // Light blue
    };
  }

  // Style for SUMMARY title (row 3)
  for (let C = range.s.c; C <= range.e.c; ++C) {
    const address = XLSX.utils.encode_cell({ r: 3, c: C });
    if (!worksheet[address]) continue;
    worksheet[address].s = {
      font: { bold: true, sz: 14, color: { rgb: "FFFFFF" } },
      fill: { fgColor: { rgb: "059669" } }, // Green
      alignment: { horizontal: "center", vertical: "center" },
    };
  }

  // Style for summary rows (rows 4-8)
  for (let R = 4; R <= 8; ++R) {
    for (let C = range.s.c; C <= 1; ++C) {
      const address = XLSX.utils.encode_cell({ r: R, c: C });
      if (!worksheet[address]) continue;
      worksheet[address].s = {
        font: { bold: C === 0, sz: 11 },
        fill: { fgColor: { rgb: C === 0 ? "D1FAE5" : "FFFFFF" } }, // Light green for labels
        alignment: {
          horizontal: C === 0 ? "left" : "right",
          vertical: "center",
        },
        border: {
          top: { style: "thin", color: { rgb: "E5E7EB" } },
          bottom: { style: "thin", color: { rgb: "E5E7EB" } },
          left: { style: "thin", color: { rgb: "E5E7EB" } },
          right: { style: "thin", color: { rgb: "E5E7EB" } },
        },
      };
    }
  }

  // Style for table header (row 10)
  const headerRow = 10;
  for (let C = range.s.c; C <= range.e.c; ++C) {
    const address = XLSX.utils.encode_cell({ r: headerRow, c: C });
    if (!worksheet[address]) continue;
    worksheet[address].s = {
      font: { bold: true, sz: 12, color: { rgb: "FFFFFF" } },
      fill: { fgColor: { rgb: "DC2626" } }, // Red for expense
      alignment: { horizontal: "center", vertical: "center" },
      border: {
        top: { style: "medium", color: { rgb: "000000" } },
        bottom: { style: "medium", color: { rgb: "000000" } },
        left: { style: "thin", color: { rgb: "000000" } },
        right: { style: "thin", color: { rgb: "000000" } },
      },
    };
  }

  // Style for data rows (alternating colors)
  for (let R = 11; R < range.e.r - 1; ++R) {
    const isEven = (R - 11) % 2 === 0;
    for (let C = range.s.c; C <= range.e.c; ++C) {
      const address = XLSX.utils.encode_cell({ r: R, c: C });
      if (!worksheet[address]) continue;
      worksheet[address].s = {
        font: { sz: 10 },
        fill: { fgColor: { rgb: isEven ? "FFFFFF" : "FEE2E2" } }, // Alternating white and light red
        alignment: {
          horizontal: C === 0 ? "center" : C === 1 ? "left" : "right",
          vertical: "center",
        },
        border: {
          top: { style: "thin", color: { rgb: "E5E7EB" } },
          bottom: { style: "thin", color: { rgb: "E5E7EB" } },
          left: { style: "thin", color: { rgb: "E5E7EB" } },
          right: { style: "thin", color: { rgb: "E5E7EB" } },
        },
      };
    }
  }

  // Add worksheet to workbook
  XLSX.utils.book_append_sheet(workbook, worksheet, "Expense Report");

  // Generate file name with timestamp
  const timestamp = moment().format("YYYYMMDD_HHmmss");
  const fullFileName = `${fileName}_${timestamp}.xlsx`;

  // Write and download file
  XLSX.writeFile(workbook, fullFileName);

  return fullFileName;
};

/**
 * Generate Excel report for income with enhanced styling and formatting
 * @param {Array} incomeData - Array of income objects
 * @param {string} fileName - Name of the file to download
 */
export const generateIncomeExcelReport = (
  incomeData,
  fileName = "Income_Report"
) => {
  // Prepare data for Excel
  const worksheetData = [];

  // Add title row
  worksheetData.push(["INCOME REPORT"]);
  worksheetData.push([
    `Generated on: ${moment().format("DD MMMM YYYY, HH:mm")}`,
  ]);
  worksheetData.push([]); // Empty row for spacing

  // Calculate summary statistics
  const totalIncome = incomeData.reduce(
    (sum, item) => sum + Number(item.amount),
    0
  );
  const averageIncome =
    incomeData.length > 0 ? totalIncome / incomeData.length : 0;
  const maxIncome =
    incomeData.length > 0
      ? Math.max(...incomeData.map((item) => Number(item.amount)))
      : 0;
  const minIncome =
    incomeData.length > 0
      ? Math.min(...incomeData.map((item) => Number(item.amount)))
      : 0;

  // Add summary section
  worksheetData.push(["SUMMARY"]);
  worksheetData.push([
    "Total Income:",
    `Rp ${addThounsandSeparators(totalIncome)}`,
  ]);
  worksheetData.push([
    "Average Income:",
    `Rp ${addThounsandSeparators(averageIncome.toFixed(2))}`,
  ]);
  worksheetData.push([
    "Highest Income:",
    `Rp ${addThounsandSeparators(maxIncome)}`,
  ]);
  worksheetData.push([
    "Lowest Income:",
    `Rp ${addThounsandSeparators(minIncome)}`,
  ]);
  worksheetData.push(["Total Transactions:", incomeData.length]);
  worksheetData.push([]); // Empty row for spacing

  // Add table headers
  worksheetData.push(["No.", "Source", "Amount (Rp)", "Date", "Month", "Year"]);

  // Add income data
  incomeData.forEach((income, index) => {
    worksheetData.push([
      index + 1,
      income.source,
      addThounsandSeparators(income.amount),
      moment(income.date).format("DD/MM/YYYY"),
      moment(income.date).format("MMMM"),
      moment(income.date).format("YYYY"),
    ]);
  });

  // Add footer
  worksheetData.push([]);
  worksheetData.push(["Report generated by Finance App"]);
  worksheetData.push([`© ${moment().format("YYYY")} - All Rights Reserved`]);

  // Create workbook and worksheet
  const workbook = XLSX.utils.book_new();
  const worksheet = XLSX.utils.aoa_to_sheet(worksheetData);

  // Set column widths - increased for better visibility
  worksheet["!cols"] = [
    { wch: 22 }, // No. / Summary Labels (expanded for "Total Transactions:")
    { wch: 30 }, // Source
    { wch: 20 }, // Amount
    { wch: 15 }, // Date
    { wch: 15 }, // Month
    { wch: 10 }, // Year
  ];

  // Merge cells for title
  worksheet["!merges"] = [
    { s: { r: 0, c: 0 }, e: { r: 0, c: 5 } }, // Title row
    { s: { r: 1, c: 0 }, e: { r: 1, c: 5 } }, // Date row
    { s: { r: 3, c: 0 }, e: { r: 3, c: 5 } }, // SUMMARY title
  ];

  // Apply styles to cells
  const range = XLSX.utils.decode_range(worksheet["!ref"]);

  // Style for title (row 0)
  for (let C = range.s.c; C <= range.e.c; ++C) {
    const address = XLSX.utils.encode_cell({ r: 0, c: C });
    if (!worksheet[address]) continue;
    worksheet[address].s = {
      font: { bold: true, sz: 16, color: { rgb: "FFFFFF" } },
      fill: { fgColor: { rgb: "1E3A8A" } }, // Dark blue
      alignment: { horizontal: "center", vertical: "center" },
    };
  }

  // Style for generated date (row 1)
  for (let C = range.s.c; C <= range.e.c; ++C) {
    const address = XLSX.utils.encode_cell({ r: 1, c: C });
    if (!worksheet[address]) continue;
    worksheet[address].s = {
      font: { italic: true, sz: 10 },
      alignment: { horizontal: "center", vertical: "center" },
      fill: { fgColor: { rgb: "E0E7FF" } }, // Light blue
    };
  }

  // Style for SUMMARY title (row 3)
  for (let C = range.s.c; C <= range.e.c; ++C) {
    const address = XLSX.utils.encode_cell({ r: 3, c: C });
    if (!worksheet[address]) continue;
    worksheet[address].s = {
      font: { bold: true, sz: 14, color: { rgb: "FFFFFF" } },
      fill: { fgColor: { rgb: "059669" } }, // Green
      alignment: { horizontal: "center", vertical: "center" },
    };
  }

  // Style for summary rows (rows 4-8)
  for (let R = 4; R <= 8; ++R) {
    for (let C = range.s.c; C <= 1; ++C) {
      const address = XLSX.utils.encode_cell({ r: R, c: C });
      if (!worksheet[address]) continue;
      worksheet[address].s = {
        font: { bold: C === 0, sz: 11 },
        fill: { fgColor: { rgb: C === 0 ? "D1FAE5" : "FFFFFF" } }, // Light green for labels
        alignment: {
          horizontal: C === 0 ? "left" : "right",
          vertical: "center",
        },
        border: {
          top: { style: "thin", color: { rgb: "E5E7EB" } },
          bottom: { style: "thin", color: { rgb: "E5E7EB" } },
          left: { style: "thin", color: { rgb: "E5E7EB" } },
          right: { style: "thin", color: { rgb: "E5E7EB" } },
        },
      };
    }
  }

  // Style for table header (row 10)
  const headerRow = 10;
  for (let C = range.s.c; C <= range.e.c; ++C) {
    const address = XLSX.utils.encode_cell({ r: headerRow, c: C });
    if (!worksheet[address]) continue;
    worksheet[address].s = {
      font: { bold: true, sz: 12, color: { rgb: "FFFFFF" } },
      fill: { fgColor: { rgb: "059669" } }, // Green for income
      alignment: { horizontal: "center", vertical: "center" },
      border: {
        top: { style: "medium", color: { rgb: "000000" } },
        bottom: { style: "medium", color: { rgb: "000000" } },
        left: { style: "thin", color: { rgb: "000000" } },
        right: { style: "thin", color: { rgb: "000000" } },
      },
    };
  }

  // Style for data rows (alternating colors)
  for (let R = 11; R < range.e.r - 1; ++R) {
    const isEven = (R - 11) % 2 === 0;
    for (let C = range.s.c; C <= range.e.c; ++C) {
      const address = XLSX.utils.encode_cell({ r: R, c: C });
      if (!worksheet[address]) continue;
      worksheet[address].s = {
        font: { sz: 10 },
        fill: { fgColor: { rgb: isEven ? "FFFFFF" : "D1FAE5" } }, // Alternating white and light green
        alignment: {
          horizontal: C === 0 ? "center" : C === 1 ? "left" : "right",
          vertical: "center",
        },
        border: {
          top: { style: "thin", color: { rgb: "E5E7EB" } },
          bottom: { style: "thin", color: { rgb: "E5E7EB" } },
          left: { style: "thin", color: { rgb: "E5E7EB" } },
          right: { style: "thin", color: { rgb: "E5E7EB" } },
        },
      };
    }
  }

  // Add worksheet to workbook
  XLSX.utils.book_append_sheet(workbook, worksheet, "Income Report");

  // Generate file name with timestamp
  const timestamp = moment().format("YYYYMMDD_HHmmss");
  const fullFileName = `${fileName}_${timestamp}.xlsx`;

  // Write and download file
  XLSX.writeFile(workbook, fullFileName);

  return fullFileName;
};
